import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { ProjectInfo } from '../detectors/project.js';

import { warn } from '../utils/logger.js';
import { getEslintDeps, getToolchainDeps } from '../utils/versions.js';

const SCRIPTS: Record<string, string> = {
  commit: 'cz',
  format: 'prettier --write .',
  'format:check': 'prettier --check .',
  lint: 'eslint .',
  'lint:fix': 'eslint . --fix',
  'lint:strict': 'eslint . --max-warnings 0',
  prepare: 'husky',
  typecheck: 'tsc --noEmit',
};

const LINT_STAGED = {
  '*.{json,md,css}': ['prettier --write'],
  '*.{ts,tsx}': ['eslint --fix', 'prettier --write'],
};

// cz-commitlint reads the commitlint.config.js already generated by this
// tool to drive its interactive prompt, so there's no second source of
// truth to keep in sync.
const COMMITIZEN_CONFIG = { path: '@commitlint/cz-commitlint' };

export function updatePackageJson(targetDir: string, info: ProjectInfo): void {
  const pkgPath = path.join(targetDir, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as Record<string, unknown>;

  const existingScripts = (pkg['scripts'] as Record<string, string>) ?? {};
  const conflicts = Object.keys(SCRIPTS).filter((key) => key in existingScripts);
  if (conflicts.length > 0) {
    warn(`Overwriting existing scripts: ${conflicts.join(', ')}`);
  }

  pkg['scripts'] = preserveKeyOrder(existingScripts, SCRIPTS);
  pkg['lint-staged'] = LINT_STAGED;

  const existingConfig = (pkg['config'] as Record<string, unknown>) ?? {};
  pkg['config'] = { ...existingConfig, commitizen: COMMITIZEN_CONFIG };

  const devDeps: Record<string, string> = { ...getToolchainDeps(), ...getEslintDeps(info) };

  const existingDeps = (pkg['devDependencies'] as Record<string, string>) ?? {};
  const depConflicts = Object.keys(devDeps).filter(
    (key) => key in existingDeps && existingDeps[key] !== devDeps[key],
  );
  if (depConflicts.length > 0) {
    warn(
      `Overwriting existing devDependency versions: ${depConflicts
        .map((key) => `${key} (${existingDeps[key]} -> ${devDeps[key]})`)
        .join(', ')}`,
    );
  }

  pkg['devDependencies'] = preserveKeyOrder(existingDeps, devDeps);

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}

function preserveKeyOrder(original: Record<string, unknown>, merged: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const key of Object.keys(original)) {
    result[key] = key in merged ? merged[key] : original[key];
  }
  for (const key of Object.keys(merged)) {
    if (!(key in result)) result[key] = merged[key];
  }
  return result;
}
